export const DGenerateSmlFilter = () => ({
  diseaseArea: null,
  language: null,
  platform: null,
  company: null,
  product: null,
  gender: null,
  ethnicity: null,
  location: null,
  stakeholder: null,
  hashtag: null,
  keyword: null,
  sentiment: null,
  symptom: null,
  mention: null,
  suggestion: null,
  age: {
    min: '',
    max: '',
  },
  volume: {
    min: '',
    max: '',
  },
});
